### PR TITLE
Support for nested indentation on pasted content

### PR DESCRIPTION
**Pull request by gjhenrique**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Stand on the shoulder of the giant @f1ames to support lists indentation in pasted content added. 
Closes https://github.com/ckeditor/ckeditor5/issues/2518

---

### Additional information
We're currently using ckeditor in one of our projects and it's a worderfull library. Thank you for open sourcing it.

Everything works fine, except the support for nested lists is a requirement. I checked that https://github.com/ckeditor/ckeditor5-paste-from-office/pull/53 was pending because of the normalization of some items. This PR tries to fix that normalization.

I rebased to master from the existing branch, fixed the conflicts and modified the required code to support it.  On top of that, I commited https://github.com/ckeditor/ckeditor5-paste-from-office/commit/fca9d7751d0fabc5ec281cc0e11d229dce8dcd8a to support the correct normalization.

Lemme know if something is missing

\cc
@Mgsy @Reinmar

### CODE REVIEW

**Comment by gjhenrique** [comment]
I just pushed 92291558e220f2a886131edf46110374790856d3 to fix a filed test build related to the removal of `<o:p>` introduced on https://github.com/ckeditor/ckeditor5-paste-from-office/pull/81

**Comment by Reinmar** [comment]
Wow :) You're a hero already! :)

@ckeditor/qa-team, could you check whether this PR doesn't break something that perhaps worked already? If there are no regressions, even if this PR doesn't handle some things perfectly, I'm all for merging it. 

@mlewand, I leave the code review to you. Similarly to the QA aspect – as long as there are no major issues, let's merge this.

**Comment by laertispappas** [comment]
Hi guys would it be possible to have this changeset released? thank you in advance.

**Comment by Reinmar** [comment]
@mlewand, there's a conflict due to changes done by @pomek recently. It should be fairly easy to resolve.

@laertispappas, we need to review the code first and once it's done and looks fine, we'll merge the PR. It will be then included in the next release.

**Comment by mlewand** [comment]
@Reinmar  Sure, I'll take a look at it tomorrow :+1:

**Comment by gjhenrique** [comment]
@mlewand 
I took the liberty to rebase from master and fix the conflict. I hope that's fine.

**Comment by Reinmar** [comment]
Awesome news :) Thanks @gjhenrique! 👏

**Pull request merged**
