### PR TITLE
Prevented spaces in spaceruns being removed when it contains a newline

### LINKED ISSUE #49: Error thrown when trying to paste entire content copied from specific Word document
Extracted from https://github.com/ckeditor/ckeditor5/issues/1474 (the sample file was posted in the mentioned issue).

1. Go to any CKEditor sample with PFO plugin enabled (e.g. https://ckeditor5.github.io/).
1. Copy entire content of the [SUITE MEMORIES.docx](https://github.com/ckeditor/ckeditor5/files/2793314/SUITE.MEMORIES.docx) file.
1. Paste into editor.

The `Uncaught TypeError: Cannot read property 'data' of undefined` error is thrown. Looks like an issue with [`normalizeSpacerunSpans()` function](https://github.com/ckeditor/ckeditor5-paste-from-office/blob/c8e0a0d9349c21984e92fb27f7c0cee7ff01df44/src/filters/space.js#L33).
From what I have checked it seems the problematic content is on page 2 in the document, rest is pasted without any errors.

### PR DESCRIPTION
**Pull request by kobsy**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Prevented an error that occurred when a spacerun contains a newline. Closes #49.

---

### CODE REVIEW

**Comment by Mgsy** [comment]
Unfortunately, I'm still able to reproduce the issue from https://github.com/ckeditor/ckeditor5-paste-from-office/issues/49.

**Comment by f1ames** [comment]
@kobsy thanks for the PR 👍 

However, the editor still throws the same error when pasting content from `SUITE.MEMORIES.docx` attached in #49.
It seems `normalizeSpacerunSpans()` function still encounters empty (with no children) `spacerun span` elements. And adding `.replace( /<span style=['"]mso-spacerun:yes['"]>[\r\n]*<\/span>/g, '' )` after the line you have added (to remove spaceless `spacerun spans`) doesn't help so I assume something may happen when HTML string is converted to `Document` object 🤔

**Comment by f1ames** [comment]
It turns out the issue here is with the regexp itself:

```js
/(<span style=['"]mso-spacerun:yes['"]>\s+)[\r\n]+(\s*<\/span>)/g,
```

the troublesome element looks like (S - space):

```html
<span style='mso-spacerun:yes'>S\r\n</span>
```

so the regexp will match like:

`$1` - `<span style='mso-spacerun:yes'>S\r`
`[\r\n]+` - `\n`
`$2` -  `</span>`

it happens because `\s*` is a greedy match for all whitespace characters so it also matches `\r`. After replacing the `span` element looks like:

```
<span style='mso-spacerun:yes'>S\r</span>
```

so there is still a one breaking character. I will try to improve the regexp.

**Comment by kobsy** [comment]
Oh! Good call! I don't think my test case included a `\r` either; I've now added it. The previous regex failed the updated test, but I swapped out that first `\s+` with `[^\S\r\n]+`, which should match whitespace _other_ than newline or carriage return (do we need to worry about `\f` or `\v`, I wonder?). The second `\s*` shouldn't need updating, since the preceding `[\r\n]+` is also greedy. 😁

**Comment by f1ames** [comment]
Thanks @kobsy, it works fine now!

I have created a new PR based on your changes #52 (I wasn't able to push anything to your branch) and added few unit tests and modified the regexp to also handle cases when there is no space on the `spacerun span` beginning (TBH it's hard to guess or find any information what kind of characters these spans may contain and it's quite cheap to cover additional cases).

**Comment by Reinmar** [comment]
I've just merged https://github.com/ckeditor/ckeditor5-paste-from-office/pull/52. Thanks @kobsy!

**Comment by kobsy** [comment]
Thanks! Happy to help! 🙂

**Pull request closed without merging**
