### PR TITLE
Docs: Expanded Paste from Word and Paste from Google Docs samples.

### PR DESCRIPTION
**Pull request by AnnaTomanek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Enhanced Paste from Word and Paste from Google Docs samples. Closes ckeditor/ckeditor5#5887.

---

### Additional information

TODO:

- [x] Expand the toolbars in Paste from Word and Paste from Google Docs sections.
- [x] Get rid of the sidebar TOC.
- [x] Change the Word sample to get rid of serif font (font family does not work in Paste from Office) and to add some colors.
- ~[ ] Add the page-like styling that we use in document editor as it resembles what you can see in Google Docs and Word, TODO: @dkonopka~

### CODE REVIEW

**Comment by Reinmar** [comment]
I'm waiting for the @dkonopka's changes with merging this.

**Comment by dkonopka** [comment]
done ✅ 

Screenshot 2020-02-27 at 09 50 06

**Comment by AnnaTomanek** [comment]
It looks like adding the page-like styles solved one problem but introduced another: the demo now is taking too much space, and since it's set to have a pre-defined height, the UX after you paste some Word content (like our own example) got worse as the editor does not autogrow and there is the scrollbar that one needs to use.



My suggestion would be to revert the last change, sorry @dkonopka :grinning: And thanks for providing it!

PS: After we fine-tuned the document editor demo in the examples as well as on our website it looks like it can be a natural place for the users to try out pasting from Word there. You can see the paged design there so I think we are covered somehow, and let's not lower the readability of the Paste from Office guides by adding it here, too.

**Comment by mlewand** [comment]
Since the PR was meant to go into the `stable` branch I added the merge from `i/5887-fix` (same hash as this PR). Also merged `stable` to `master`.

**Pull request merged**
